#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#
#
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: cn.edu.guet.springbootdemo.bean
#
#logging:
#  level:
#    cn.edu.guet.springbootdemo.mapper: DEBUG


# 端口
server:
  port: 8088


#spring:
#  # mysql
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.78.211.33:3306/OA?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: Aliyun1154615101@

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa_project?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: THEO1126


# mybatis 加载 bean和 xml ，映射路径配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.guet.springbootdemo.bean
  configuration:
    map-underscore-to-camel-case: true

# 日志输出
logging:
  level:
    cn.edu.guet.springbootdemo.mapper: DEBUG
  file:
    name: D:\program\LanqiaoWeb\springboot-demo\root.log
